### ISSUE TITLE
Vaststellen release v1.0

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-tabellen-bevragen#14]
Deze API wordt zeer binnenkort gerealiseerd voor de RvIG pilot. Daarom moet er nu zo snel mogelijk een versie worden vastgesteld

**Comment by fsamwel** [comment]
@JohanBoer kan jij (z.s.m.) de huidige stand op de master branch vastzetten in een release v1.0?

**Comment by JohanBoer** [comment]
Done
